buildscript {
    ext {
        springVersion = '4.1.1'
    }
}

plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'spotify'
version = '1.13.0-pre9c'

java {
    withJavadocJar()
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += "-parameters"
}

tasks.withType(Javadoc).configureEach {
    options.addStringOption('Xdoclint:none', '-quiet')
}

repositories {
    mavenCentral()
    maven {
        url 'https://jitpack.io'
    }
}

publishing {
    repositories {
        maven {
            name = 'spotify-dependencies'
            url = project.findProperty('publishingUrl') ?: ""
            credentials {
                username = project.findProperty('publishingUsername') ?: ""
                password = project.findProperty('publishingPassword') ?: ""
            }
        }
    }
    publications {
        register('mavenJava', MavenPublication) {
            artifactId = 'spotify-dependencies'

            //noinspection GroovyAssignabilityCheck
            from components.java

            versionMapping {
                usage('java-api') {
                    fromResolutionOf('runtimeClasspath')
                }
                usage('java-runtime') {
                    fromResolutionResult()
                }
            }

            pom {
                name = 'spotify-dependencies'
                description = 'Basic dependencies for all my Spotify projects'
                url = 'https://github.com'
                licenses {
                    license {
                        name = 'MIT License'
                        url = 'https://opensource.org'
                    }
                }
                developers {
                    developer {
                        id = 'selbi'
                        name = 'Selbi'
                        email = 'selbix@web.de'
                    }
                }
            }
        }
    }
}

dependencies {
    implementation "org.springframework.boot:spring-boot-starter-web:$springVersion"
    implementation 'se.michaelthelin.spotify:spotify-web-api-java:10.0.0-RC7'
    implementation 'org.jsoup:jsoup:1.16.2'
    implementation 'com.github.albfernandez:juniversalchardet:2.4.0'
}
